Resolve CI failures
First, `rails/rails@main` requires Ruby >= 3.3.1, so every Ruby 3.2 job
paired with RAILS_VERSION=main fails bundler's dependency resolution
before any tests run:

```
Because every version of rails depends on Ruby >= 3.3.1
  and Gemfile depends on rails >= 0,
  Ruby >= 3.3.1 is required.
So, because current Ruby version is = 3.2.11,
  version solving has failed.
```

Next, the `playwright-ruby-client` and the npm `playwright` package must
have matching versions.

Adjust the CI configuration to install a `playwright` dependency to
match the version output by `Playwright::COMPATIBLE_PLAYWRIGHT_VERSION`.

Finally, every playwright system test now raises the following error:

```
NoMethodError: undefined method `to_sym' for {}:Hash
    vendor/bundle/.../axe-core-api-4.13.0/lib/axe/api/value_object.rb:92:in `coerce_class'
```

`axe`.js returns `null` for unset attributes, like the `impact` of a
rule with no violations. In JavaScript, `typeof null === "object"`, and
`capybara-playwright-driver` gem's `Node#wrap_node` doesn't special-case
those values. Instead, it tries to traverse `null` in the same as any
other `Object`.

The new private `AxeAuditor#denullify` method transforms empty objects
into `null`.